In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [3]:
data_file = 'groceries.csv'
THRESHOLD = 0.5
MIN_COUNT = 10
min_confidance = THRESHOLD

In [4]:
def get_transactions(data_file, sep=','):
    
    # Delimiter
    data_file_delimiter = sep
    transactions = []
    
    with open(data_file, 'r') as temp_f:
        
        # Read the lines
        lines = temp_f.readlines()

        for l in lines:
            
            columns = l.split(data_file_delimiter)
            columns = [col.strip('\n') for col in columns]
            transactions.append(columns)
            
    # Close file
    temp_f.close()
    
    return transactions

In [31]:
transactions = get_transactions(data_file, sep=',')

In [32]:
#transactions = transactions[0:100]

In [33]:
min_support = MIN_COUNT/len(transactions)

In [34]:
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False
9831,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9832,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
9833,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9834,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [41]:
df.shape

(9835, 169)

In [35]:
min_support

0.0010167768174885613

In [36]:
result = apriori(df, min_support=min_support, use_colnames=True)

In [37]:
result.shape

(13492, 2)

In [27]:
result['length'] = result['itemsets'].apply(lambda x: len(x))
result

        support                                           itemsets  length
0      0.008033                            (Instant food products)       1
1      0.033452                                         (UHT-milk)       1
2      0.003559                                 (abrasive cleaner)       1
3      0.003254                                 (artif. sweetener)       1
4      0.017692                                    (baking powder)       1
...         ...                                                ...     ...
13487  0.001017  (whole milk, whipped/sour cream, yogurt, root ...       6
13488  0.001017  (oil, whole milk, yogurt, tropical fruit, root...       6
13489  0.001322  (pip fruit, whole milk, yogurt, tropical fruit...       6
13490  0.001322  (whole milk, yogurt, rolls/buns, tropical frui...       6
13491  0.001118  (whole milk, whipped/sour cream, yogurt, tropi...       6

[13492 rows x 3 columns]

In [38]:
association_result = association_rules(result, metric="confidence", min_threshold=min_confidance)

In [39]:
min_support

0.0010167768174885613

In [40]:
association_result

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(baking powder),(whole milk),0.017692,0.255516,0.009253,0.522989,2.046793,0.004732,1.560725
1,(cereals),(whole milk),0.005694,0.255516,0.003660,0.642857,2.515917,0.002206,2.084555
2,(cocoa drinks),(whole milk),0.002237,0.255516,0.001322,0.590909,2.312611,0.000750,1.819850
3,(cooking chocolate),(whole milk),0.002542,0.255516,0.001322,0.520000,2.035097,0.000672,1.551008
4,(honey),(whole milk),0.001525,0.255516,0.001118,0.733333,2.870009,0.000729,2.791815
...,...,...,...,...,...,...,...,...,...
5824,"(whole milk, rolls/buns, tropical fruit, root ...",(yogurt),0.002034,0.139502,0.001322,0.650000,4.659439,0.001038,2.458566
5825,"(yogurt, rolls/buns, tropical fruit, root vege...",(whole milk),0.001830,0.255516,0.001322,0.722222,2.826524,0.000854,2.680142
5826,"(whole milk, whipped/sour cream, yogurt, tropi...",(other vegetables),0.001627,0.193493,0.001118,0.687500,3.553107,0.000804,2.580824
5827,"(whole milk, whipped/sour cream, tropical frui...",(yogurt),0.001932,0.139502,0.001118,0.578947,4.150107,0.000849,2.043683
5828,"(whipped/sour cream, yogurt, tropical fruit, r...",(whole milk),0.001729,0.255516,0.001118,0.647059,2.532361,0.000677,2.109371

In [22]:
association_result.lift.describe()

count    5829.000000
mean        3.455241
std         1.811099
min         1.956825
25%         2.471778
50%         2.935237
75%         3.754859
max        30.811404
Name: lift, dtype: float64